name: Blazor WASM CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Build Tailwind CSS
        run: npx tailwindcss -i ./Themes/Theme.css -o ./wwwroot/css/theme.css

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release
